version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: peergate-backend
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=8080
    restart: unless-stopped
    networks:
      - peergate-network

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: peergate-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - peergate-network

networks:
  peergate-network:
    driver: bridge
